apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: todo-web
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  # httpPipeline:
  #   handlers:
  #     - type: middleware.http.oauth2
  #       name: oauth2
  mtls:
    allowedClockSkew: 15m
    enabled: true
    workloadCertTTL: 24h
