apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todomvc-web
spec:
  hosts:
    - todo.red-badger.com
  gateways:
    - istio-system/todo-gateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: todomvc-web
